os:
  - windows
  - linux
  - osx

matrix:
  include:
    - os: linux
      dist: xenial

language: python
sudo: required
python:
  - "3.6"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libdbus-1-dev libdbus-glib-1-dev --yes; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x SpotifyLyrics.pyw; fi

script:
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb-run ./SpotifyLyrics.pyw; fi

before_deploy:
  - pip install pyinstaller
  - pyinstaller SpotifyLyrics.pyw

deploy:
  provider: releases
  pre-release: true
  skip_cleanup: true
  api_key: ${GH_TOKEN}