matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      before_install:
        - sudo apt-get install libdbus-1-dev libdbus-glib-1-dev --yes
        - chmod +x SpotifyLyrics.pyw
        - pip install --upgrade pip
      language: python
      cache: pip
      python:
        - 3.6
      before_deploy:
        - pip install pyinstaller
        - pyinstaller SpotifyLyrics.pyw -F -w -i icon.ico --add-data "icon.png:."
    #- os: osx
    #  language: generic
    #  before_install:
    #    - brew update
    #    - pip install --upgrade pip
    #  install:
    #    - pip install -r requirements.txt
    #  before_deploy:
    #    - pip install pyinstaller
    #    - pyinstaller SpotifyLyrics.pyw -F -w -i icon.ico --add-data "icon.png:."
    #- os: windows
    #  language: cpp
    #  before_install:
    #    - choco upgrade chocolatey -y -v -d
    #    - choco install python -v -d
    #  before_deploy:
    #    - pip install pyinstaller
    #    - pyinstaller SpotifyLyrics.pyw -F -w -i icon.ico --add-data "icon.png;."

before_script:
  - export PYTHONPATH=$PYTHONPATH:$PWD

script:
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb-run ./SpotifyLyrics.pyw; fi
  - cd tests/
  - python -m unittest discover . "*_test.py"

deploy:
  provider: releases
  pre-release: true
  skip_cleanup: true
  api_key: ${GH_TOKEN}
  file:
    - dist/SpotifyLyrics
    - dist/SpotifyLyrics.exe
    - dist/SpotifyLyrics.app
  on:
    repo: SimonIT/spotifylyrics
    tags: true
    all_branches: true